version: '3.8'

services:
  backend:
    build: ./src/backend
    ports:
      - "5000:5000"
    volumes:
      - "./src/backend:/app"
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:5000
    env_file:
      - ./src/backend/.env

  frontend:
    build: ./src/frontend
    volumes:
      - "./src/frontend:/app"
      - "./frontend/node_modules"
    ports:
      - "80:8080"
    command: npm run serve
